// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckinpartsController from "./checkinparts_controller"
application.register("checkinparts", CheckinpartsController)

import CleanersappointmentsController from "./cleanersappointments_controller"
application.register("cleanersappointments", CleanersappointmentsController)

import EndDateCalculationController from "./end_date_calculation_controller"
application.register("end-date-calculation", EndDateCalculationController)

import FaqtoggleController from "./faqtoggle_controller"
application.register("faqtoggle", FaqtoggleController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormpartsController from "./formparts_controller"
application.register("formparts", FormpartsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TimeAndPriceEstimationsController from "./time_and_price_estimations_controller"
application.register("time-and-price-estimations", TimeAndPriceEstimationsController)
