// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CleanersappointmentsController from "./cleanersappointments_controller"
application.register("cleanersappointments", CleanersappointmentsController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TimeAndPriceEstimationsController from "./time_and_price_estimations_controller"
application.register("time-and-price-estimations", TimeAndPriceEstimationsController)
